Index of Alphabet In C implementation, Readme Changes
codinasion/codinasion-programme pull request #1288
Opened 2022-07-29 19:29 UTC by SpirosArk

### Why:

Closes #1137 

### What's being changed:

### Check off the following:

- [x ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-07-30 14:09 UTC, KikiManjaro requested changes
Minor fixes related to #1295

2022-07-30 14:09 UTC, KikiManjaro commented on programme/index-of-alphabet/index-of-alphabet.c
> +//Program that accepts a char as an input and returns it's position in alphabet
```suggestion
//Programme that accepts a char as an input and returns it's position in alphabet
```

2022-07-30 14:09 UTC, KikiManjaro commented on programme/volume-of-cylinder/volume-of-cylinder.jl
> +#Program to calculate volumeOfCylinder
```suggestion
#Programme to calculate volumeOfCylinder
```

2022-07-30 14:29 UTC, SpirosArk commented
I accepted suggestions please rereview

2022-07-30 17:24 UTC, KikiManjaro commented on programme/index-of-alphabet/index-of-alphabet.c
> +    }
```suggestion
    if (input >= 97){
        position = input - 'a' + 1;
    }
    else{
        position = input - 'A' + 1;
    }
```

2022-07-30 17:29 UTC, KikiManjaro commented
You've made a mistake and modified volume in this MR, this one should only refer to index-of-alphabet

2022-07-30 17:31 UTC, SpirosArk commented
I accepted all suggested commits cause i saw them from cellphone

2022-07-30 17:37 UTC, KikiManjaro approved these changes

2022-07-31 08:22 UTC, harshraj8843 commented
Tracked in #1294

2022-07-31 08:22 UTC, closed without merging