Create square-root-of-number.jl
codinasion/codinasion-programme pull request #1289
Opened 2022-07-29 19:36 UTC by SpirosArk

### Why:

Closes #1095 

### What's being changed:

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-07-30 14:08 UTC, KikiManjaro requested changes
Minor fixes related to #1295

2022-07-30 14:08 UTC, KikiManjaro commented on programme/square-root-of-number/square-root-of-number.jl
> +#Program to calculate the square root of a given input
```suggestion
#Programme to calculate the square root of a given input
```

2022-07-30 17:15 UTC, KikiManjaro approved these changes

2022-07-31 08:00 UTC, harshraj8843 approved these changes
👍🏻

2022-07-31 08:01 UTC, merged