Volume
codinasion/codinasion-programme pull request #1290
Opened 2022-07-29 20:10 UTC by SpirosArk

### Why:

Closes #1045 

### What's being changed:

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-07-30 14:08 UTC, KikiManjaro requested changes
Minor fixes related to #1295

2022-07-30 14:08 UTC, KikiManjaro commented on programme/index-of-alphabet/index-of-alphabet.c
> +//Program that accepts a char as an input and returns it's position in alphabet
```suggestion
//Programme that accepts a char as an input and returns it's position in alphabet
```

2022-07-30 14:08 UTC, KikiManjaro commented on programme/volume-of-cone/volume-of-cone.jl
> +#Program to calculate volumeOfCone
```suggestion
#Programme to calculate volumeOfCone
```

2022-07-30 17:16 UTC, KikiManjaro approved these changes

2022-07-30 17:25 UTC, KikiManjaro commented on programme/index-of-alphabet/index-of-alphabet.c
> +    }
```suggestion
    if (input >= 97){
        position = input - 'a' + 1;
    }
    else{
        position = input - 'A' + 1;
    }
```

2022-07-30 17:27 UTC, KikiManjaro commented
You've made a mistake and modified index-of-alphabet in this MR, this one should only refer to volume

2022-07-30 17:31 UTC, PrajwalBorkar commented
> You've made a mistake and modified index-of-alphabet in this MR, this one should only refer to volume

Actually it is showing here because other pr is not merged which contains this file.

2022-07-30 17:37 UTC, SpirosArk commented
What should I change? I am confused right now...

2022-07-30 17:43 UTC, KikiManjaro commented
@SpirosArk Don't worry, everything will be ok when your other MR will be merged 👌

For the next time just think about creating a new branch from master for each programs you add, the new code you add from a MR that is not merged yet should not be in an other MR that solves an other issue

2022-07-30 17:45 UTC, PrajwalBorkar commented
> What should I change? I am confused right now...

No need to do anything now, just make sure that you include only one code in one branch e.g. in this volume branch includes changes related to volume code instead of having other files which is the alphabet.c file.

2022-07-30 17:45 UTC, SpirosArk commented
Ok, I understand. Each file commit in different branch. Thank you!

2022-07-30 17:47 UTC, PrajwalBorkar approved these changes
I think this is ready to be merged. Thanks for the changes :)

2022-07-31 08:28 UTC, harshraj8843 approved these changes
👍🏻

2022-07-31 08:28 UTC, merged

2022-07-31 08:35 UTC, harshraj8843 commented
> Ok, I understand. Each file commit in different branch. Thank you!

Not necessarily each file in a different branch, but we should create solutions for different programmes in different branches

So, we can put the `solution` file and updated `README.md` file in one branch and then create a PR

In this way, PR(s) are easy to review

2022-07-31 08:39 UTC, SpirosArk commented
When I update the Readme it asks me to create new branch. It does not accept to commit the change to an already existing branch. Let's say we have created earlier volume.c, when I will change the volume Readme it will prompt me to commit either on master or on another branch. This is where I mess up

2022-07-31 08:46 UTC, harshraj8843 commented
> When I update the Readme it asks me to create new branch. It does not accept to commit the change to an already existing branch. Let's say we have created earlier volume.c, when I will change the volume Readme it will prompt me to commit either on master or on another branch. This is where I mess up

okay, you are adding files directly to github (I thought you are committing from local)

In this case, you can create different files to different branches 👍🏻 

> **Note** Please create a new branch from `master`, so that PR(s) will not contain files from different PR(s)

2022-07-31 09:12 UTC, SpirosArk commented
These days I am on vacation so I commit through cell phone written scripts. When I am at my local machine I do it as I should. With puling -commiting- pushing