Create volume-of-cylinder.jl
codinasion/codinasion-programme pull request #1292
Opened 2022-07-30 12:13 UTC by SpirosArk

### Why:

Closes #1035 

### What's being changed:

### Check off the following:

- [x ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-07-30 14:07 UTC, KikiManjaro requested changes
Minor fixes related to #1295

2022-07-30 14:07 UTC, KikiManjaro commented on programme/volume-of-cylinder/volume-of-cylinder.jl
> +#Program to calculate volumeOfCylinder
```suggestion
#Programme to calculate volumeOfCylinder
```

2022-07-30 14:27 UTC, SpirosArk commented
I committed changes please re review

2022-07-30 17:16 UTC, KikiManjaro approved these changes

2022-07-31 08:07 UTC, harshraj8843 approved these changes
👍🏻

2022-07-31 08:07 UTC, merged