Random odd in java
codinasion/codinasion-programme pull request #1294
Opened 2022-07-30 12:34 UTC by SpirosArk

### Why:

Closes #1120 

### What's being changed:

### Check off the following:

- [ x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-07-30 14:05 UTC, KikiManjaro requested changes
Minor fixes related to #1295

2022-07-30 14:05 UTC, KikiManjaro commented on programme/index-of-alphabet/index-of-alphabet.c
> +//Program that accepts a char as an input and returns it's position in alphabet
```suggestion
//Programme that accepts a char as an input and returns it's position in alphabet
```

2022-07-30 14:05 UTC, KikiManjaro commented on programme/random-odd-number/random-odd-number.java
> +//Program to generate random odd number in range using Java
```suggestion
//Programme to generate random odd number in range using Java
```

2022-07-30 14:05 UTC, KikiManjaro commented on programme/volume-of-cylinder/volume-of-cylinder.jl
> +#Program to calculate volumeOfCylinder
```suggestion
#Programme to calculate volumeOfCylinder
```

2022-07-30 17:21 UTC, KikiManjaro commented on programme/random-odd-number/random-odd-number.java
> +        }
```suggestion
        while (random_int % 2 == 0){
            random_int = (int)Math.floor(Math.random()*(endRange-startRange+1)+startRange);
        }
```

2022-07-30 17:22 UTC, KikiManjaro commented on programme/index-of-alphabet/index-of-alphabet.c
> +    }
```suggestion
    if (input >= 97){
        position = input - 'a' + 1;
    }
    else{
        position = input - 'A' + 1;
    }
```

2022-07-30 17:29 UTC, KikiManjaro commented
You've made a mistake and modified index-of-alphabet and volume in this MR, this one should only refer to Random odd

2022-07-31 08:18 UTC, harshraj8843 approved these changes
👍🏻

2022-07-31 08:20 UTC, harshraj8843 commented
Hey @SpirosArk , please consider different solutions in different PR(s) 👍🏻

2022-07-31 08:20 UTC, merged