Added sum-of-numbers.cpp
codinasion/codinasion-programme pull request #1308
Opened 2022-08-04 09:12 UTC by TimTProd

### Why:

Closes #1056 

### What's being changed:

Added sum-of-numbers.cpp

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-08-04 20:20 UTC, SpirosArk requested changes
Tried to run the program, It gets into an infinite loop and only accepts numbers without calculating the result

2022-08-05 08:00 UTC, TimTProd commented
Stopping the input stream in this code is done with EOF. After a new commit the input stream is stopped by pressing Enter

2022-08-05 19:29 UTC, SpirosArk approved these changes, later dismissed

2022-08-06 12:15 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2022-08-06 12:15 UTC, merged