Check prime number
codinasion/codinasion-programme pull request #826
Opened 2022-06-11 18:02 UTC by MadhuS-1605

### Why:

Closes #ISSUE_NUMBER

### What's being changed:
added a new golang program to check prime number

### Check off the following:

- [✓] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [✓] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

2022-06-14 23:13 UTC, harshraj8843 requested changes

2022-06-15 05:42 UTC, MadhuS-1605 commented on programme/check-prime-number/check-prime-number.go
> +	}
Sorry! Will update with new code

2022-06-15 05:48 UTC, MadhuS-1605 commented on programme/check-prime-number/check-prime-number.go
> +	}
Updated the changes

2022-06-16 04:40 UTC, harshraj8843 approved these changes
👍🏻

2022-06-16 04:40 UTC, merged